# Generated by Django 3.0.9 on 2020-08-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
